"""Primitive surface-cell construction for a requested Miller plane.

The in-plane pair is chosen by minimising the longer of the two lengths, then
their sum, then the area.  ``aristotle-lean-reference/RequestProject/SurfacePlaneBasis.lean`` proves that
this rule always returns a *primitive* cell of the plane lattice --- the pair it
selects realises the two successive minima, and such a pair has index one
(``Cellstine.abs_pairDet_eq_one_of_minimal``) --- and that the reported cell
angle always lies in ``(60, 120]`` degrees, the final ``b -> b - a`` step being
the hexagonal case and nothing else (``Cellstine.two_abs_gramInner_le_of_minima``,
``Cellstine.hexagonal_of_cos_ge_half``, ``Cellstine.shear_gram_of_hexagonal``).
"""

from __future__ import annotations

import math
from typing import List, Sequence, Tuple

import numpy as np

from ...core import reduction, symmetry3d
from ...core.species import expand_species
from ...core.lattice import vector_angle_deg
from ...io import native as io_mod


def _translation_maps_structure(structure: io_mod.PoscarData, translation: Sequence[float], tolerance: float = 1e-5) -> bool:
    positions = np.mod(np.asarray(structure.positions_direct, dtype=float), 1.0)
    if positions.shape[0] == 0:
        return True
    species = expand_species(structure.species, structure.counts, natoms=structure.natoms)
    translation_array = np.asarray(translation, dtype=float)
    shifted = np.mod(positions + translation_array, 1.0)
    # Pairwise minimum-image fractional differences between every shifted atom
    # and every original atom, all at once instead of an O(n^2) Python loop.
    diff = shifted[:, None, :] - positions[None, :, :]
    diff -= np.round(diff)
    coincident = np.all(np.abs(diff) <= tolerance, axis=2)
    codes = np.unique(np.asarray(species), return_inverse=True)[1]
    same_species = codes[:, None] == codes[None, :]
    matched = np.any(coincident & same_species, axis=1)
    return bool(np.all(matched))


# The pure translations of each named centring, as fractional vectors of the
# conventional cell.  ``Cellstine.Centering.centering_classification`` proves
# that these five sets, together with the trivial one, are the *only* groups a
# cell can have whose non-zero translations are all half-cell vectors, so the
# lookup below is exhaustive for that case; ``R`` is the rhombohedral setting,
# whose translations are thirds.
_CENTERING_TRANSLATIONS: dict[str, tuple[tuple[float, float, float], ...]] = {
    "A": ((0.0, 0.5, 0.5),),
    "B": ((0.5, 0.0, 0.5),),
    "C": ((0.5, 0.5, 0.0),),
    "I": ((0.5, 0.5, 0.5),),
    "F": ((0.0, 0.5, 0.5), (0.5, 0.0, 0.5), (0.5, 0.5, 0.0)),
    "R": ((2.0 / 3.0, 1.0 / 3.0, 1.0 / 3.0), (1.0 / 3.0, 2.0 / 3.0, 2.0 / 3.0)),
}

_TRANSLATION_SYMPREC = 1e-4


def _pure_translations(structure: io_mod.PoscarData, symprec: float = _TRANSLATION_SYMPREC) -> np.ndarray:
    """Return every fractional translation that maps the cell onto itself.

    The zero translation is always included, so the array has ``m`` rows where
    ``m`` is the index of the input cell in the lattice of its own translations.
    """

    species = expand_species(structure.species, structure.counts, natoms=structure.natoms)
    return symmetry3d.translation_group(
        np.asarray(structure.lattice, dtype=float),
        np.asarray(structure.positions_direct, dtype=float),
        species,
        symprec=float(symprec),
    )


def _centering_label(translations: np.ndarray, tolerance: float = 1e-5) -> str:
    """Return the centring letter of a translation group.

    ``P`` is a cell whose only pure translation is the identity.  A group that
    is not one of the six standard centrings --- which is what a supercell of a
    smaller cell has --- is reported as ``X<m>`` with ``m`` its order, so the
    report never claims a centring the cell does not have.
    """

    vectors = np.mod(np.asarray(translations, dtype=float).reshape(-1, 3), 1.0)
    if len(vectors) <= 1:
        return "P"
    for letter, expected in _CENTERING_TRANSLATIONS.items():
        target = np.asarray(expected, dtype=float)
        if len(vectors) != len(target) + 1:
            continue
        difference = vectors[:, None, :] - target[None, :, :]
        difference -= np.round(difference)
        matched = np.any(np.all(np.abs(difference) <= tolerance, axis=2), axis=0)
        if bool(np.all(matched)):
            return letter
    return f"X{len(vectors)}"


def _centering_type(structure: io_mod.PoscarData) -> str:
    """Return the centring letter of ``structure``."""

    return _centering_label(_pure_translations(structure))


def _standard_centering_matrices() -> dict[str, np.ndarray]:
    """Return the primitive basis of each standard centring, in cell coordinates.

    Each matrix is a basis of the lattice generated by the unit translations and
    the centring translations of its letter, and its determinant is the
    reciprocal of the number of those translations --- ``1``, ``1/2`` and ``1/4``
    for ``P``, ``A``/``B``/``C``/``I`` and ``F``.  Both facts are proved in
    ``aristotle-lean-reference/RequestProject/CenteringLattice.lean``
    (``Cellstine.Centering.span_centeringBasis``,
    ``Cellstine.Centering.det_centeringBasis``).
    """

    return {
        "P": np.array(
            [
                [1.0, 0.0, 0.0],
                [0.0, 1.0, 0.0],
                [0.0, 0.0, 1.0],
            ],
            dtype=float,
        ),
        "F": np.array(
            [
                [0.0, 0.5, 0.5],
                [0.5, 0.0, 0.5],
                [0.5, 0.5, 0.0],
            ],
            dtype=float,
        ),
        "I": np.array(
            [
                [-0.5, 0.5, 0.5],
                [0.5, -0.5, 0.5],
                [0.5, 0.5, -0.5],
            ],
            dtype=float,
        ),
        "A": np.array(
            [
                [1.0, 0.0, 0.0],
                [0.0, 0.5, 0.5],
                [0.0, -0.5, 0.5],
            ],
            dtype=float,
        ),
        # The rows are ordered so that every basis is right handed: the plain
        # (b, B, -B) order of the other two letters would give this one a
        # negative determinant.
        "B": np.array(
            [
                [0.0, 1.0, 0.0],
                [-0.5, 0.0, 0.5],
                [0.5, 0.0, 0.5],
            ],
            dtype=float,
        ),
        "C": np.array(
            [
                [0.0, 0.0, 1.0],
                [0.5, 0.5, 0.0],
                [-0.5, 0.5, 0.0],
            ],
            dtype=float,
        ),
    }


def _primitive_translation_lattice(structure: io_mod.PoscarData) -> tuple[np.ndarray, str]:
    """Return the primitive translation lattice of ``structure`` and its centring.

    The lattice returned is spanned by the cell's *own* pure translations, not
    by a guess from the four standard centring vectors: a cell that happens to
    be a supercell of a smaller one is reduced too, so the surface cell built on
    it is genuinely primitive rather than a repeat of the primitive one.  A
    standard centring keeps its textbook basis, which is already reduced and
    keeps the built cells bit-for-bit what they were.
    """

    lattice = np.asarray(structure.lattice, dtype=float)
    translations = _pure_translations(structure)
    centering = _centering_label(translations)
    matrices = _standard_centering_matrices()
    if centering in matrices:
        return matrices[centering] @ lattice, centering
    species = expand_species(structure.species, structure.counts, natoms=structure.natoms)
    basis, _ = symmetry3d.translation_lattice_basis(
        lattice,
        np.asarray(structure.positions_direct, dtype=float),
        species,
        symprec=_TRANSLATION_SYMPREC,
    )
    return basis @ lattice, centering


def _reciprocal_normal(lattice: np.ndarray, miller: tuple[int, int, int]) -> np.ndarray:
    h, k, l = (int(value) for value in miller)
    if h == 0 and k == 0 and l == 0:
        raise ValueError("Miller indices cannot all be zero")
    reciprocal_rows = np.linalg.inv(np.asarray(lattice, dtype=float)).T
    normal = float(h) * reciprocal_rows[0] + float(k) * reciprocal_rows[1] + float(l) * reciprocal_rows[2]
    norm = float(np.linalg.norm(normal))
    if norm <= 1e-12:
        raise ValueError("could not determine a surface normal for the requested Miller indices")
    return normal / norm


def _select_surface_pair(
    candidate_vectors: np.ndarray,
    normal: np.ndarray,
    *,
    tolerance: float = 1e-7,
) -> tuple[np.ndarray, np.ndarray]:
    """Pick the surface cell out of a set of in-plane lattice vectors.

    The rule is the one ``aristotle-lean-reference/RequestProject/SurfacePlaneBasis.lean`` analyses: the
    longer of the two lengths first, then their sum, then the area, with ties
    broken by the position of the pair in the length-then-coordinate ordering of
    the candidates.  The winner realises the two successive minima of the plane
    lattice, so it spans that lattice and not a sublattice of it, and its cell
    angle lies in ``(60, 120]`` degrees once the final shear has been applied.
    """

    candidate_vectors = np.asarray(candidate_vectors, dtype=float).reshape(-1, 3)
    normal = np.asarray(normal, dtype=float)
    if candidate_vectors.shape[0] < 2:
        raise ValueError("could not find primitive in-plane surface vectors")
    candidate_lengths = np.linalg.norm(candidate_vectors, axis=1)
    rounded = np.round(candidate_vectors, 12)
    sort_order = np.lexsort((rounded[:, 2], rounded[:, 1], rounded[:, 0], candidate_lengths))
    candidate_vectors = candidate_vectors[sort_order]
    candidate_lengths = candidate_lengths[sort_order]

    # Vectorised pairwise scan over all i < j pairs (row-major triangular order
    # matching the original nested loop, so tie-breaking is identical).
    idx_i, idx_j = np.triu_indices(candidate_vectors.shape[0], k=1)
    first_vectors = candidate_vectors[idx_i]
    second_vectors = candidate_vectors[idx_j]
    cross = np.cross(first_vectors, second_vectors)
    oriented_area = cross @ normal
    area = np.abs(oriented_area)
    valid = area > tolerance
    if not np.any(valid):
        raise ValueError("could not find a non-singular primitive surface cell")
    valid_positions = np.nonzero(valid)[0]
    first_lengths = candidate_lengths[idx_i][valid]
    second_lengths = candidate_lengths[idx_j][valid]
    max_lengths = np.maximum(first_lengths, second_lengths)
    sum_lengths = first_lengths + second_lengths
    valid_area = area[valid]
    # Stable lexicographic selection: primary max length, then sum length, then
    # area; ties keep the earliest pair (stable sort over triangular order).
    winner_local = np.lexsort((valid_area, sum_lengths, max_lengths))[0]
    winner = int(valid_positions[winner_local])
    surface_a = np.array(first_vectors[winner], dtype=float, copy=True)
    surface_b = np.array(second_vectors[winner], dtype=float, copy=True)
    if float(oriented_area[winner]) < 0.0:
        surface_a, surface_b = surface_b, surface_a
    angle_deg = vector_angle_deg(surface_a, surface_b)
    if angle_deg <= 60.0 + 1e-8:
        surface_b = surface_b - surface_a
    return surface_a, surface_b


def _primitive_surface_vectors_from_lattice(
    primitive_lattice: np.ndarray,
    normal: np.ndarray,
    *,
    search: int = 4,
    tolerance: float = 1e-7,
) -> tuple[np.ndarray, np.ndarray]:
    """Return the surface cell by enumerating a box of integer coefficients.

    Kept as the fallback of :func:`_primitive_surface_vectors`, for the case
    where the plane cannot be written as an exact integer form on the primitive
    lattice.  The box is a heuristic: a skew cell can put the short in-plane
    vectors outside any fixed range of coefficients, and then the pair returned
    here is a valid but needlessly long cell of the plane lattice.
    """

    primitive_lattice = np.asarray(primitive_lattice, dtype=float)
    normal = np.asarray(normal, dtype=float)
    # Vectorised enumeration of all integer combinations in the search box.
    rng = np.arange(-int(search), int(search) + 1)
    grid = np.stack(np.meshgrid(rng, rng, rng, indexing="ij"), axis=-1).reshape(-1, 3).astype(float)
    # Reproduce ``i*a + j*b + k*c`` term-by-term so the floating point result is
    # bit-identical to the original scalar accumulation.
    vectors = (
        grid[:, 0:1] * primitive_lattice[0]
        + grid[:, 1:2] * primitive_lattice[1]
        + grid[:, 2:3] * primitive_lattice[2]
    )
    lengths_all = np.linalg.norm(vectors, axis=1)
    nonzero = ~np.all(grid == 0.0, axis=1)
    in_plane = np.abs(vectors @ normal) <= tolerance
    keep = nonzero & in_plane & (lengths_all > tolerance)
    return _select_surface_pair(vectors[keep], normal, tolerance=tolerance)


def _surface_vector_search_limit(miller: Sequence[int]) -> int:
    return max(5, 2 * max(abs(int(value)) for value in miller) + 3)


def _integer_plane_form(
    bulk_lattice: np.ndarray,
    primitive_lattice: np.ndarray,
    miller: Sequence[int],
    *,
    max_denominator: int = 720,
) -> tuple[int, int, int] | None:
    """Return the Miller indices of the plane *in the primitive basis*.

    A vector with integer coefficients ``m`` on the primitive lattice lies in
    the ``(hkl)`` plane of the bulk cell exactly when ``m . f = 0``, where
    ``f = (P B^-1) (h, k, l)`` for the primitive rows ``P`` and the bulk rows
    ``B``.  The change of basis is a centring matrix, so ``f`` is rational with
    a small denominator; it is cleared here and the result divided by its own
    common factor.  ``None`` is returned when no denominator up to
    ``max_denominator`` clears it, which is the signal to fall back on the box
    search.
    """

    bulk = np.asarray(bulk_lattice, dtype=float)
    primitive = np.asarray(primitive_lattice, dtype=float)
    indices = np.asarray([float(value) for value in miller], dtype=float)
    weights = primitive @ np.linalg.inv(bulk) @ indices
    magnitude = float(np.max(np.abs(weights)))
    if not np.all(np.isfinite(weights)) or magnitude <= 0.0:
        return None
    for denominator in range(1, int(max_denominator) + 1):
        scaled = weights * float(denominator)
        rounded = np.rint(scaled)
        if float(np.max(np.abs(scaled - rounded))) > 1e-7 * max(1.0, float(np.max(np.abs(scaled)))):
            continue
        values = [int(value) for value in rounded]
        if not any(values):
            continue
        common = 0
        for value in values:
            common = math.gcd(common, abs(value))
        return (values[0] // common, values[1] // common, values[2] // common)
    return None


def _primitive_surface_vectors(
    bulk_lattice: np.ndarray,
    primitive_lattice: np.ndarray,
    normal: np.ndarray,
    miller: Sequence[int],
    *,
    tolerance: float = 1e-7,
) -> tuple[np.ndarray, np.ndarray]:
    """Return the primitive in-plane cell of the ``(hkl)`` plane.

    The plane lattice is built exactly --- the integer form of the plane on the
    primitive basis, its kernel basis from one extended Euclid step
    (``cellstine.core.reduction.plane_form_kernel_basis``), then a
    Lagrange--Gauss reduction of that basis --- so the two successive minima of
    the plane lattice are always found, whatever the shape of the cell.  The
    eight combinations ``p u + q v`` with ``p, q`` in ``{-1, 0, 1}`` contain
    every lattice vector no longer than the second minimum that can appear in
    the winning pair, so the selection rule below sees exactly the candidates
    that matter and the answer is unchanged wherever the old box search was
    already wide enough.
    """

    form = _integer_plane_form(bulk_lattice, primitive_lattice, miller)
    if form is None:
        return _primitive_surface_vectors_from_lattice(
            primitive_lattice,
            normal,
            search=_surface_vector_search_limit(miller),
            tolerance=tolerance,
        )
    primitive = np.asarray(primitive_lattice, dtype=float)
    coefficients = reduction.plane_form_kernel_basis(np.asarray(form, dtype=np.int64))
    plane_basis = coefficients.astype(float) @ primitive
    reduced, _ = reduction.plane_reduce(plane_basis)
    combinations = np.array(
        [[p, q] for p in (-1, 0, 1) for q in (-1, 0, 1) if (p, q) != (0, 0)],
        dtype=float,
    )
    candidates = combinations @ reduced
    return _select_surface_pair(candidates, normal, tolerance=tolerance)


def _surface_coordinate_frame(surface_a: np.ndarray, surface_b: np.ndarray, normal: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    x_axis = np.asarray(surface_a, dtype=float) / float(np.linalg.norm(surface_a))
    y_axis = np.asarray(surface_b, dtype=float) - float(np.dot(surface_b, x_axis)) * x_axis
    y_norm = float(np.linalg.norm(y_axis))
    if y_norm <= 1e-12:
        raise ValueError("surface in-plane vectors are linearly dependent")
    y_axis /= y_norm
    if float(np.dot(np.cross(x_axis, y_axis), normal)) < 0.0:
        y_axis *= -1.0
    basis_2d = np.array(
        [
            [float(np.dot(surface_a, x_axis)), float(np.dot(surface_b, x_axis))],
            [float(np.dot(surface_a, y_axis)), float(np.dot(surface_b, y_axis))],
        ],
        dtype=float,
    )
    return x_axis, y_axis, basis_2d


def _deduplicate_scalar_levels(values: Sequence[float], tolerance: float) -> list[float]:
    arr = np.asarray(values, dtype=float).ravel()
    if arr.size == 0:
        return []
    arr.sort()
    tol = float(tolerance)
    # Greedy clustering identical to scanning the sorted values and keeping a
    # value whenever it is more than ``tolerance`` away from the last kept one.
    # ``searchsorted`` jumps directly to the next kept value, so the loop runs
    # once per surviving level instead of once per (highly degenerate) sample.
    levels: list[float] = [float(arr[0])]
    last = levels[0]
    size = arr.size
    while True:
        nxt = int(np.searchsorted(arr, last + tol, side="right"))
        if nxt >= size:
            break
        last = float(arr[nxt])
        levels.append(last)
    return levels


def _group_surface_atoms_by_species(
    atoms: Sequence[tuple[str, np.ndarray, tuple[str, str, str] | None]],
    species_order: Sequence[str],
) -> tuple[np.ndarray, list[int], list[str], list[tuple[str, str, str]] | None]:
    grouped: dict[str, list[np.ndarray]] = {str(symbol): [] for symbol in species_order}
    grouped_flags: dict[str, list[tuple[str, str, str] | None]] = {str(symbol): [] for symbol in species_order}
    order = [str(symbol) for symbol in species_order]
    for symbol, direct, flags in atoms:
        if symbol not in grouped:
            grouped[symbol] = []
            grouped_flags[symbol] = []
            order.append(symbol)
        grouped[symbol].append(np.asarray(direct, dtype=float))
        grouped_flags[symbol].append(flags)

    positions = []
    counts = []
    species = []
    flags_out: list[tuple[str, str, str]] = []
    has_flags = any(flags is not None for _, _, flags in atoms)
    for symbol in order:
        if not grouped[symbol]:
            continue
        species.append(symbol)
        counts.append(len(grouped[symbol]))
        positions.extend(grouped[symbol])
        if has_flags:
            for flags in grouped_flags[symbol]:
                flags_out.append(tuple(flags or ("T", "T", "T")))
    return np.asarray(positions, dtype=float), counts, species, flags_out if has_flags else None


def _integer_shift_grid_3d(limit: int) -> np.ndarray:
    values = np.arange(-int(limit), int(limit) + 1, dtype=float)
    return np.stack(np.meshgrid(values, values, values, indexing="ij"), axis=-1).reshape(-1, 3)


def _integer_shift_grid_2d(limit: int) -> np.ndarray:
    values = np.arange(-int(limit), int(limit) + 1, dtype=float)
    return np.stack(np.meshgrid(values, values, indexing="ij"), axis=-1).reshape(-1, 2)


def _build_native_primitive_surface_cell(
    structure: io_mod.PoscarData,
    miller: tuple[int, int, int],
    *,
    layers: int,
    vacuum: float,
    search_padding: int = 5,
    tolerance: float = 1e-5,
    require_bulk_period: bool = True,
) -> io_mod.PoscarData:
    """Return the primitive ``(hkl)`` cell holding ``layers`` atomic layers.

    With ``vacuum > 0`` the cell is a slab: its height is the span of the atomic
    layers plus the requested empty gap, so the vacuum thickness of the written
    cell is exactly ``vacuum``.

    With ``vacuum == 0`` the cell is instead the *bulk* cell of the same
    orientation: its height is the distance from the first layer to the first
    repeat of that layer above the stack, so the stack tiles space without
    either a gap or a duplicated layer, and the atomic density is the bulk one.
    That is only a crystal when the requested layer count is a whole number of
    stacking periods -- an ``fcc`` ``(111)`` stack repeats every three layers --
    and ``require_bulk_period`` asks for the count to be checked, so a request
    that would silently emit a stacking fault is refused instead.
    """

    layers = int(layers)
    if layers < 1:
        raise ValueError("layers must be at least 1")
    if float(vacuum) < 0.0:
        raise ValueError("vacuum must be non-negative")

    bulk_lattice = np.asarray(structure.lattice, dtype=float)
    primitive_lattice, centering = _primitive_translation_lattice(structure)
    normal = _reciprocal_normal(bulk_lattice, miller)
    surface_a, surface_b = _primitive_surface_vectors(
        bulk_lattice,
        primitive_lattice,
        normal,
        miller,
        tolerance=1e-7,
    )
    if float(np.dot(np.cross(surface_a, surface_b), normal)) < 0.0:
        surface_a, surface_b = surface_b, surface_a
    x_axis, y_axis, basis_2d = _surface_coordinate_frame(surface_a, surface_b, normal)

    species_expanded = expand_species(structure.species, structure.counts, natoms=structure.natoms)
    flags_expanded = structure.selective_flags or [None] * structure.natoms
    base_direct = np.asarray(structure.positions_direct, dtype=float)
    base_cartesian = io_mod.direct_to_cartesian(base_direct, bulk_lattice)
    base_projections = base_cartesian @ normal
    base_projected_2d = np.column_stack((base_cartesian @ x_axis, base_cartesian @ y_axis))

    image_limit = max(layers + search_padding, 6)
    shifts = _integer_shift_grid_3d(image_limit)
    shift_cartesian = shifts @ bulk_lattice
    shift_projections = shift_cartesian @ normal
    shift_projected_2d = np.column_stack((shift_cartesian @ x_axis, shift_cartesian @ y_axis))
    basis_inverse_transposed = np.linalg.inv(basis_2d).T

    all_projections = (base_projections[:, None] + shift_projections[None, :]).reshape(-1)
    all_levels = _deduplicate_scalar_levels(all_projections, tolerance)
    start_candidates = [index for index, level in enumerate(all_levels) if level >= -tolerance]
    if not start_candidates:
        raise ValueError("could not locate a starting atomic layer for the requested surface")
    start_index = start_candidates[0]
    selected_levels = all_levels[start_index : start_index + layers]
    if len(selected_levels) < layers:
        raise ValueError("could not generate enough atomic layers; try a smaller layer count or check the bulk cell")

    uv_tolerance = max(1e-4, float(np.linalg.norm(surface_a) + np.linalg.norm(surface_b)) * 1e-7)
    inplane_basis = np.array(
        [[basis_2d[0, 0], basis_2d[1, 0]], [basis_2d[0, 1], basis_2d[1, 1]]],
        dtype=float,
    )

    def _layer_atoms(level: float) -> list[tuple[str, np.ndarray, tuple[str, str, str] | None]]:
        """Return the distinct atoms of the plane at ``level``, in ``uv`` coordinates."""

        layer_unique: list[tuple[str, np.ndarray, tuple[str, str, str] | None]] = []
        # Per-species accumulator of already-accepted uv points for this layer,
        # so the duplicate test against existing points is a single vectorised
        # min-image distance computation rather than a Python inner loop.
        existing_by_species: dict[str, list[np.ndarray]] = {}
        for atom_index in range(structure.natoms):
            matching_shifts = np.abs(base_projections[atom_index] + shift_projections - float(level)) <= tolerance
            if not np.any(matching_shifts):
                continue
            projected_2d = base_projected_2d[atom_index] + shift_projected_2d[matching_shifts]
            uv_values = projected_2d @ basis_inverse_transposed
            uv_values = np.mod(uv_values, 1.0)
            uv_values[np.isclose(uv_values, 1.0, atol=tolerance)] = 0.0
            uv_values[np.isclose(uv_values, 0.0, atol=tolerance)] = 0.0
            symbol = str(species_expanded[atom_index])
            accepted = existing_by_species.setdefault(symbol, [])
            flags_value = None if flags_expanded[atom_index] is None else tuple(flags_expanded[atom_index])
            # The periodic images of a single atom that land on this level all map
            # to the same in-plane fractional point, so collapse exact (to ~1e-9)
            # duplicates first (preserving first-occurrence order). This is far
            # finer than ``uv_tolerance`` and cannot merge genuinely distinct
            # sites, but removes the hundreds of identical images that otherwise
            # drive the dedup loop.
            if uv_values.shape[0] > 1:
                _, first_occurrence = np.unique(np.round(uv_values, 9), axis=0, return_index=True)
                uv_values = uv_values[np.sort(first_occurrence)]
            for uv in uv_values:
                if accepted:
                    existing_array = np.asarray(accepted, dtype=float)
                    delta = uv[None, :] - existing_array
                    delta -= np.round(delta)
                    cartesian = delta @ inplane_basis
                    distances = np.sqrt(np.einsum("ij,ij->i", cartesian, cartesian))
                    if np.any(distances <= uv_tolerance):
                        continue
                uv_array = np.asarray(uv, dtype=float)
                accepted.append(uv_array)
                layer_unique.append((symbol, uv_array, flags_value))
        return layer_unique

    layer_cache: dict[int, list[tuple[str, np.ndarray, tuple[str, str, str] | None]]] = {}

    def _layer(index: int) -> list[tuple[str, np.ndarray, tuple[str, str, str] | None]]:
        cached = layer_cache.get(index)
        if cached is None:
            cached = _layer_atoms(all_levels[start_index + index])
            layer_cache[index] = cached
        return cached

    def _layer_signature(index: int) -> tuple[tuple[str, float, float], ...]:
        """Return a comparable, origin-fixed description of one atomic plane."""

        entries: list[tuple[str, float, float]] = []
        for symbol, uv, _ in _layer(index):
            u = round(float(uv[0]) % 1.0, 6) % 1.0
            v = round(float(uv[1]) % 1.0, 6) % 1.0
            entries.append((symbol, u, v))
        return tuple(sorted(entries))

    available_levels = len(all_levels) - start_index

    def _stacking_period() -> int | None:
        """Return the number of layers after which the stack repeats itself.

        The cell is a crystal exactly when translating it along the normal maps
        the layer sequence onto itself, which -- since the in-plane coordinates
        are read modulo the surface lattice -- is what comparing the layer
        signatures tests.  A period is accepted only when it survives twice its
        own length of layers, so a coincidence between two neighbouring planes
        cannot pass for one.
        """

        cap = max(1, min(available_levels // 3, max(4 * structure.natoms + 8, 48)))
        for period in range(1, cap + 1):
            height = float(all_levels[start_index + period] - all_levels[start_index])
            span = min(2 * period, available_levels - period)
            if span < period:
                break
            matches = True
            for index in range(span):
                spacing = float(all_levels[start_index + index + period] - all_levels[start_index + index])
                if abs(spacing - height) > tolerance or _layer_signature(index + period) != _layer_signature(index):
                    matches = False
                    break
            if matches:
                return period
        return None

    slab_thickness = float(selected_levels[-1] - selected_levels[0]) if len(selected_levels) > 1 else 0.0
    if float(vacuum) > 0.0:
        c_length = slab_thickness + float(vacuum)
    else:
        # A vacuum-free cell is the bulk cell of this orientation: it ends where
        # the layer above the stack begins, so the stack tiles space with the
        # bulk atomic density and no layer is repeated across the boundary.
        if available_levels <= layers:
            raise ValueError("could not locate the repeat of the first layer; try a smaller layer count")
        c_length = float(all_levels[start_index + layers] - all_levels[start_index])
        if require_bulk_period:
            period = _stacking_period()
            if period is None:
                raise ValueError(
                    f"the ({int(miller[0])} {int(miller[1])} {int(miller[2])}) stack of this cell does not repeat "
                    "within the searched range of layers, so it has no vacuum-free cell with a perpendicular "
                    "c axis; ask for a vacuum instead"
                )
            if layers % period:
                lower = layers - layers % period
                suggestion = f"{lower} or {lower + period}" if lower else f"{period}"
                raise ValueError(
                    f"a vacuum-free ({int(miller[0])} {int(miller[1])} {int(miller[2])}) cell repeats every "
                    f"{period} atomic layers, so {layers} layers would emit a stacking fault; "
                    f"ask for {suggestion} layers, or for a vacuum"
                )
    if c_length <= 1e-12:
        raise ValueError("surface c axis would have zero length")
    # Emit the slab in the canonical surface frame: the two in-plane vectors lie
    # in Cartesian xy with a along +x, and c is the outward normal along +z.  The
    # fractional coordinates below are unchanged by this rotation, but every
    # downstream stage -- adsorbate placement, moire search, interface matching --
    # can then assume a planar cell instead of re-deriving the surface frame.
    surface_lattice = np.array(
        [
            [basis_2d[0, 0], basis_2d[1, 0], 0.0],
            [basis_2d[0, 1], basis_2d[1, 1], 0.0],
            [0.0, 0.0, c_length],
        ],
        dtype=float,
    )
    if len(selected_levels) > 1:
        interlayer_spacing = float(selected_levels[1] - selected_levels[0])
    elif start_index + 1 < len(all_levels):
        interlayer_spacing = float(all_levels[start_index + 1] - selected_levels[0])
    else:
        interlayer_spacing = 0.0
    lower_vacuum = min(max(interlayer_spacing, 0.0), float(vacuum))

    atoms: list[tuple[str, np.ndarray, tuple[str, str, str] | None]] = []
    for layer_index, level in enumerate(selected_levels):
        layer_unique = _layer(layer_index)
        if not layer_unique:
            raise ValueError(f"surface layer {layer_index + 1} did not contain any atoms")
        w_value = (lower_vacuum + (float(level) - float(selected_levels[0]))) / c_length
        for species, uv, flags in layer_unique:
            atoms.append((species, np.array([float(uv[0]), float(uv[1]), float(w_value)], dtype=float), flags))

    positions_direct, counts, species, flags = _group_surface_atoms_by_species(atoms, structure.species or sorted(set(species_expanded)))
    return io_mod.PoscarData(
        comment=(
            f"{structure.comment} | primitive {centering}-lattice surface cell "
            f"({int(miller[0])} {int(miller[1])} {int(miller[2])})"
        ),
        lattice=surface_lattice,
        species=species,
        counts=counts,
        positions_direct=positions_direct,
        positions_cartesian=io_mod.direct_to_cartesian(positions_direct, surface_lattice),
        coordinate_mode="Direct",
        selective_dynamics=bool(structure.selective_dynamics),
        selective_flags=flags,
    )


def _structure_from_transform(structure: io_mod.PoscarData, transform: np.ndarray, tolerance: float = 1e-8) -> io_mod.PoscarData:
    if np.allclose(transform[2], np.array([0, 0, 1], dtype=float), atol=tolerance) and np.allclose(
        transform[:2, 2],
        np.zeros(2, dtype=float),
        atol=tolerance,
    ):
        return _structure_from_inplane_transform(structure, transform[:2, :2], tolerance=tolerance)

    lattice_old = np.asarray(structure.lattice, dtype=float)
    lattice_new = transform @ lattice_old
    inverse_new = np.linalg.inv(lattice_new)

    search_pad = max(2, int(np.max(np.abs(transform))) + 1)
    shifts_3d = _integer_shift_grid_3d(search_pad)
    collected_positions: List[np.ndarray] = []
    collected_array = np.empty((0, 3), dtype=float)
    collected_flags: List[Tuple[str, str, str]] | None = [] if structure.selective_flags is not None else None
    expanded_flags = structure.selective_flags or []

    for atom_index, base_direct in enumerate(np.asarray(structure.positions_direct, dtype=float)):
        images = base_direct + shifts_3d
        new_directs = io_mod.direct_to_cartesian(images, lattice_old) @ inverse_new
        inside = np.all((-tolerance <= new_directs) & (new_directs <= 1.0 + tolerance), axis=1)
        wrapped_all = np.mod(new_directs[inside], 1.0)
        if wrapped_all.shape[0] == 0:
            continue
        # Collapse exact (to ~1e-9) duplicate images first, preserving order.
        if wrapped_all.shape[0] > 1:
            _, first_occurrence = np.unique(np.round(wrapped_all, 9), axis=0, return_index=True)
            wrapped_all = wrapped_all[np.sort(first_occurrence)]
        flag_value = tuple(expanded_flags[atom_index]) if collected_flags is not None else None
        for wrapped in wrapped_all:
            if collected_array.shape[0]:
                difference = wrapped[None, :] - collected_array
                difference -= np.round(difference)
                if np.any(np.all(np.abs(difference) <= tolerance, axis=1)):
                    continue
            collected_positions.append(wrapped)
            collected_array = np.vstack((collected_array, wrapped[None, :]))
            if collected_flags is not None:
                collected_flags.append(flag_value)

    if not collected_positions:
        raise ValueError("surface transform did not capture any atoms; try a simpler Miller index")

    positions_direct = np.array(collected_positions, dtype=float)
    positions_cartesian = io_mod.direct_to_cartesian(positions_direct, lattice_new)
    multiplicity = int(round(abs(np.linalg.det(transform))))
    counts = [int(count) * multiplicity for count in structure.counts]
    return io_mod.PoscarData(
        comment=f"{structure.comment} | oriented surface cell",
        lattice=lattice_new,
        species=list(structure.species),
        counts=counts,
        positions_direct=positions_direct,
        positions_cartesian=positions_cartesian,
        coordinate_mode="Direct",
        selective_dynamics=bool(structure.selective_dynamics),
        selective_flags=collected_flags,
    )


def _structure_from_inplane_transform(
    structure: io_mod.PoscarData,
    matrix_2d: np.ndarray,
    tolerance: float = 1e-8,
) -> io_mod.PoscarData:
    matrix = np.asarray(matrix_2d, dtype=float)
    determinant = int(round(abs(np.linalg.det(matrix))))
    if determinant == 0:
        raise ValueError("in-plane supercell matrix must have a non-zero determinant")

    lattice_old = np.asarray(structure.lattice, dtype=float)
    transform_3d = np.array(
        [
            [matrix[0, 0], matrix[0, 1], 0.0],
            [matrix[1, 0], matrix[1, 1], 0.0],
            [0.0, 0.0, 1.0],
        ],
        dtype=float,
    )
    lattice_new = transform_3d @ lattice_old
    inverse_2d = np.linalg.inv(matrix)

    search_pad = max(2, int(np.max(np.abs(matrix))) + determinant + 1)
    shifts_2d = _integer_shift_grid_2d(search_pad)
    species_expanded = expand_species(structure.species, structure.counts, natoms=structure.natoms)
    flags_expanded = structure.selective_flags or [None] * structure.natoms
    collected_atoms: list[tuple[str, np.ndarray, tuple[str, str, str] | None]] = []
    # Per-species accumulator of accepted fractional positions so each new image
    # is tested against the existing ones with a single vectorised min-image
    # comparison rather than a Python scan over all collected atoms.
    existing_by_species: dict[str, list[np.ndarray]] = {}

    for atom_index, base_direct in enumerate(np.asarray(structure.positions_direct, dtype=float)):
        shifted_2d = base_direct[:2] + shifts_2d
        new_2d = shifted_2d @ inverse_2d
        inside = np.all((-tolerance <= new_2d) & (new_2d <= 1.0 + tolerance), axis=1)
        candidates_2d = new_2d[inside]
        if candidates_2d.shape[0] == 0:
            continue
        wrapped_all = np.empty((candidates_2d.shape[0], 3), dtype=float)
        wrapped_all[:, 0] = candidates_2d[:, 0]
        wrapped_all[:, 1] = candidates_2d[:, 1]
        wrapped_all[:, 2] = base_direct[2]
        wrapped_all = np.mod(wrapped_all, 1.0)
        wrapped_all[np.isclose(wrapped_all, 1.0, atol=tolerance)] = 0.0
        wrapped_all[np.isclose(wrapped_all, 0.0, atol=tolerance)] = 0.0
        # Collapse exact (to ~1e-9) duplicate images first, preserving first
        # occurrence: far finer than ``tolerance`` so it cannot merge distinct
        # sites, but removes the many identical images from the shift grid.
        if wrapped_all.shape[0] > 1:
            _, first_occurrence = np.unique(np.round(wrapped_all, 9), axis=0, return_index=True)
            wrapped_all = wrapped_all[np.sort(first_occurrence)]
        symbol = str(species_expanded[atom_index])
        accepted = existing_by_species.setdefault(symbol, [])
        flags_value = None if flags_expanded[atom_index] is None else tuple(flags_expanded[atom_index])
        for wrapped in wrapped_all:
            if accepted:
                existing_array = np.asarray(accepted, dtype=float)
                difference = wrapped[None, :] - existing_array
                difference -= np.round(difference)
                if np.any(np.all(np.abs(difference) <= tolerance, axis=1)):
                    continue
            accepted.append(wrapped)
            collected_atoms.append((symbol, wrapped, flags_value))

    expected_atoms = determinant * structure.natoms
    if len(collected_atoms) != expected_atoms:
        raise ValueError(
            f"in-plane surface transform captured {len(collected_atoms)} atoms, expected {expected_atoms}; "
            "try a simpler matrix or check the input cell"
        )

    positions_direct, counts, species, flags = _group_surface_atoms_by_species(
        collected_atoms,
        structure.species or sorted(set(species_expanded)),
    )
    return io_mod.PoscarData(
        comment=f"{structure.comment} | in-plane transformed surface cell",
        lattice=lattice_new,
        species=species,
        counts=counts,
        positions_direct=positions_direct,
        positions_cartesian=io_mod.direct_to_cartesian(positions_direct, lattice_new),
        coordinate_mode="Direct",
        selective_dynamics=bool(structure.selective_dynamics),
        selective_flags=flags,
    )
