"""Provenance strings for the structures CELLSTINE writes.

Every generated POSCAR carries one comment line, and that line is the only
place a downstream stage can read where a structure came from.  The line is
therefore built to a single shape::

    Generated by CELLSTINE <stage> stage | <note> | ... | Made by Sarwin Chandran

The notes in the middle accumulate as a structure passes from stage to stage --
``Miller (1 1 1)``, ``interface with cu_...``, ``vacancy atom_003`` -- while the
leading field always names the stage that wrote the file and the signature
always sits at the end.  :func:`restage_comment` performs that update: it reads
the notes out of an incoming comment, drops the old stage field and the old
signature, and re-emits the line for the new stage.
"""

from __future__ import annotations

import re
from typing import Iterable

__all__ = [
    "SIGNATURE",
    "STAGE_PREFIX",
    "comment_notes",
    "restage_comment",
    "stage_comment",
    "stage_of",
]

SIGNATURE = "Made by Sarwin Chandran"
STAGE_PREFIX = "Generated by CELLSTINE"

#: Comment lines longer than this drop their oldest notes.  POSCAR itself does
#: not limit the line, but an unbounded one is unreadable and grows without end
#: as a structure is passed from stage to stage.
MAX_COMMENT_LENGTH = 240

_STAGE_FIELD = re.compile(
    r"^(?:generated by\s+)?cellstine\s*(?P<stage>.*?)\s*(?:stage)?$",
    re.IGNORECASE,
)


def _fields(comment: str) -> list[str]:
    return [field.strip() for field in str(comment).split("|")]


def _is_signature(field: str) -> bool:
    return field.casefold() == SIGNATURE.casefold()


def _is_stage_field(field: str) -> bool:
    return "cellstine" in field.casefold() and bool(_STAGE_FIELD.match(field))


def stage_of(comment: str) -> str | None:
    """Return the stage named by ``comment``, or ``None`` if it names none."""

    for field in _fields(comment):
        if _is_stage_field(field):
            match = _STAGE_FIELD.match(field)
            stage = (match.group("stage") if match else "").strip()
            return stage or None
    return None


def comment_notes(comment: str) -> list[str]:
    """Return the descriptive fields of ``comment``.

    The stage field and the signature are dropped; everything else is kept in
    order, including a plain comment written by hand (``graphene``), which is
    how the name of an input structure survives into its descendants.
    """

    notes: list[str] = []
    for field in _fields(comment):
        if not field or _is_signature(field) or _is_stage_field(field):
            continue
        if field not in notes:
            notes.append(field)
    return notes


def _assemble(stage: str, notes: Iterable[str]) -> str:
    kept = [str(note).strip() for note in notes if str(note).strip()]
    head = f"{STAGE_PREFIX} {str(stage).strip()} stage"
    while True:
        line = " | ".join([head, *kept, SIGNATURE])
        if len(line) <= MAX_COMMENT_LENGTH or not kept:
            return line
        kept.pop(0)


def stage_comment(stage: str, *notes: str) -> str:
    """Return a fresh comment line for ``stage``."""

    return _assemble(stage, notes)


def restage_comment(previous: str, stage: str, *notes: str) -> str:
    """Return ``previous`` re-emitted for ``stage`` with ``notes`` appended."""

    existing = comment_notes(previous)
    appended = [str(note).strip() for note in notes if str(note).strip()]
    return _assemble(stage, [*existing, *(note for note in appended if note not in existing)])
