"""Checks on the equivalent-site sweep.

The symmetry engine labels every atom with the lowest index of the sites it is
linked to by the site permutations of the operations it found.  The statements
behind that are proved in ``RequestProject/SiteOrbits.lean``: a chain of
generator steps joins two sites exactly when they lie in one orbit of the
generated group (``Cellstine.siteLinked_iff_mem_orbit``), and the reported label is
the least index of the orbit, so two atoms share a label exactly when they are
equivalent (``Cellstine.orbitRep_eq_iff_siteLinked``, ``Cellstine.orbitRep_le``).
"""

from __future__ import annotations

import itertools
import random

import numpy as np
import pytest

from cellstine.core import symmetry3d


def _components(permutations, count):
    """Orbit representatives from an independent breadth-first search."""

    neighbours = [set() for _ in range(count)]
    for permutation in permutations:
        for site, image in enumerate(permutation):
            neighbours[site].add(int(image))
            neighbours[int(image)].add(site)
    representative = list(range(count))
    seen = [False] * count
    for start in range(count):
        if seen[start]:
            continue
        stack = [start]
        seen[start] = True
        orbit = []
        while stack:
            site = stack.pop()
            orbit.append(site)
            for other in neighbours[site]:
                if not seen[other]:
                    seen[other] = True
                    stack.append(other)
        least = min(orbit)
        for site in orbit:
            representative[site] = least
    return representative


def _generated_group(permutations, count):
    """Every permutation in the group generated by ``permutations``."""

    identity = tuple(range(count))
    group = {identity}
    frontier = [identity]
    generators = [tuple(int(value) for value in permutation) for permutation in permutations]
    while frontier:
        current = frontier.pop()
        for generator in generators:
            product = tuple(generator[value] for value in current)
            if product not in group:
                group.add(product)
                frontier.append(product)
    return group


@pytest.mark.parametrize("seed", range(6))
def test_the_sweep_finds_the_connected_components(seed):
    rng = random.Random(seed)
    count = 12
    permutations = []
    for _ in range(3):
        order = list(range(count))
        rng.shuffle(order)
        # Restrict the movement so that several orbits survive.
        block = rng.randrange(2, 5)
        order = [value if value % block else index for index, value in enumerate(order)]
        if len(set(order)) == count:
            permutations.append(order)
    if not permutations:
        permutations = [list(range(count))]
    table = np.asarray(permutations, dtype=np.int64)

    swept = symmetry3d._orbits_from_permutations(table, count)
    assert list(swept) == _components(permutations, count)
    assert all(int(swept[index]) <= index for index in range(count))


@pytest.mark.parametrize("seed", range(4))
def test_the_components_are_the_orbits_of_the_generated_group(seed):
    rng = random.Random(100 + seed)
    count = 7
    permutations = []
    for _ in range(2):
        order = list(range(count))
        rng.shuffle(order)
        permutations.append(order)
    table = np.asarray(permutations, dtype=np.int64)

    swept = symmetry3d._orbits_from_permutations(table, count)
    group = _generated_group(permutations, count)
    for site in range(count):
        orbit = {element[site] for element in group}
        assert int(swept[site]) == min(orbit)
        for other in range(count):
            assert (int(swept[site]) == int(swept[other])) == (other in orbit)


def test_a_single_long_cycle_collapses_to_one_orbit():
    count = 9
    cycle = [(index + 1) % count for index in range(count)]
    swept = symmetry3d._orbits_from_permutations(np.asarray([cycle], dtype=np.int64), count)
    assert list(swept) == [0] * count


def test_the_identity_alone_leaves_every_site_its_own_orbit():
    count = 5
    identity = list(range(count))
    swept = symmetry3d._orbits_from_permutations(np.asarray([identity], dtype=np.int64), count)
    assert list(swept) == identity


def test_reported_groups_of_a_decorated_cell_are_the_orbits():
    """The equivalent-atom map of a decorated cell agrees with the sweep."""

    lattice = np.eye(3) * 4.0
    positions = np.array(
        [
            [0.0, 0.0, 0.0],
            [0.5, 0.5, 0.0],
            [0.5, 0.0, 0.5],
            [0.0, 0.5, 0.5],
            [0.25, 0.25, 0.25],
            [0.75, 0.75, 0.75],
        ]
    )
    species = ["Na"] * 4 + ["Cl"] * 2
    rotations, translations = symmetry3d.symmetry_operations(lattice, positions, species)
    mapping = symmetry3d.equivalent_atom_map(lattice, positions, species, rotations, translations)
    permutations = symmetry3d.site_permutations(lattice, positions, species, rotations, translations)

    assert list(mapping) == _components([list(row) for row in permutations], len(positions))
    # Every operation maps an atom onto one with the same label.
    for permutation in permutations:
        for site, image in enumerate(permutation):
            assert mapping[site] == mapping[int(image)]
    # Atoms of different species are never merged.
    for left, right in itertools.combinations(range(len(positions)), 2):
        if species[left] != species[right]:
            assert mapping[left] != mapping[right]
