"""I/O utilities for reading and writing VASP POSCAR/CONTCAR files.

The routines are intentionally simple, returning numpy arrays for
lattice vectors and atomic positions.  Only the subset of POSCAR
features used in the moire finder/generator (scale factor, lattice
vectors, atom counts, coordinates) is implemented; additional
functionality can be added later.

The code is pure Python/NumPy with minimal dependencies.
"""

import numpy as np
from typing import Tuple, List


def parse_poscar(path: str) -> Tuple[np.ndarray, np.ndarray, List[int], List[str]]:
    """Read a POSCAR/CONTCAR and return lattice, positions, counts, types.

    Returns
    -------
    lattice : (3,3) ndarray
        Cartesian lattice vectors (scaled by the scale factor).
    positions : (N,3) ndarray
        Atomic coordinates in Cartesian space (regardless of input mode).
    counts : list of int
        Number of atoms for each species, in the order given.
    types : list of str
        Chemical symbols corresponding to ``counts`` (empty list if
        unspecified).
    """
    with open(path, 'r') as f:
        lines = f.read().splitlines()

    if len(lines) < 8:
        raise ValueError(f"File {path} does not look like a POSCAR")

    scale = float(lines[1].split()[0])
    lattice = np.array([list(map(float, lines[i].split())) for i in range(2, 5)])
    lattice *= scale

    # atom species and counts may occupy one or two lines depending on
    # style; we attempt to detect both cases.
    tokens5 = lines[5].split()
    tokens6 = lines[6].split()
    if all(tok.isalpha() for tok in tokens5):
        types = tokens5
        counts = list(map(int, tokens6))
        coord_start = 8
    else:
        types = []
        counts = list(map(int, tokens5))
        coord_start = 7

    natoms = sum(counts)
    coords = np.array([list(map(float, lines[i].split()[:3])) for i in range(coord_start, coord_start + natoms)])

    # if the file used "Direct" coordinates, convert to Cartesian
    if lines[coord_start - 1].lower().startswith('d'):
        coords = coords @ lattice  # assume row vectors

    return lattice, coords, counts, types


def write_poscar(path: str,
                  lattice: np.ndarray,
                  positions: np.ndarray,
                  counts: List[int],
                  types: List[str] = None,
                  comment: str = "Generated by moire") -> None:
    """Write a simple POSCAR file from the given data.

    Only `Direct` coordinate output is currently supported; the
    lattice is written with scale factor 1.0.  ``types`` may be an
    empty list if atom symbols are unknown.
    """
    with open(path, 'w') as f:
        f.write(comment.rstrip() + "\n")
        f.write("1.0\n")
        for vec in lattice:
            f.write("  %16.12f %16.12f %16.12f\n" % tuple(vec))
        if types:
            f.write(" ".join(types) + "\n")
        f.write(" ".join(str(x) for x in counts) + "\n")
        f.write("Direct\n")
        # convert positions to direct coordinates
        invlat = np.linalg.inv(lattice)
        direct = positions @ invlat
        for p in direct:
            f.write("  %16.12f %16.12f %16.12f\n" % tuple(p))
