"""High-level superstructure generation stage.

Made by Sarwin Chandran.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import List, Sequence

from . import generator as generator_backend


@dataclass
class MakeRun:
    output_path: Path
    selected_index: int
    angle_deg: float
    total_atoms: int


def _slug(value: str) -> str:
    safe = []
    for char in value:
        if char.isalnum() or char in {"-", "_"}:
            safe.append(char)
        else:
            safe.append("_")
    return "".join(safe).strip("_") or "structure"


def generate_from_results(
    results_file: str,
    *,
    index: int,
    interlayer_distance: float,
    output_path: str | None = None,
    output_dir: str | None = None,
    tolerance: int = 1,
    tolerance_float: float = 1e-4,
    zfix: float | None = None,
) -> MakeRun:
    top_poscar, bottom_poscar, records, payload = generator_backend.parse_results(results_file)
    by_index = {int(record["idx"]): record for record in records}
    if index not in by_index:
        raise ValueError(f"index {index} not found in {results_file}")

    record = by_index[index]
    lattice_out, positions_direct, counts, species, flags = generator_backend.build_supercell(
        top_poscar,
        bottom_poscar,
        record,
        shift1_cart=(0.0, 0.0, float(interlayer_distance)),
        preserve_layer="2",
        tolerance=tolerance,
        tolerance_float=tolerance_float,
        zfix=zfix,
    )

    total_atoms = int(sum(counts))
    angle_deg = float(record.get("angle", 0.0))
    if output_path is None:
        destination_dir = Path(results_file).resolve().parent if output_dir is None else Path(output_dir).resolve()
        destination_dir.mkdir(parents=True, exist_ok=True)
        output_name = (
            f"stack_idx{index:03d}_ang{angle_deg:.4f}_atoms{total_atoms}_"
            f"{_slug(Path(bottom_poscar).stem)}-below_{_slug(Path(top_poscar).stem)}-above.vasp"
        )
        output_path = str(destination_dir / output_name)

    generator_backend.write_supercell_poscar(
        output_path,
        lattice_out,
        positions_direct,
        counts,
        species,
        flags,
        comment="Generated by moire make stage | Made by Sarwin Chandran",
    )

    return MakeRun(
        output_path=Path(output_path).resolve(),
        selected_index=index,
        angle_deg=angle_deg,
        total_atoms=total_atoms,
    )


def generate_many_from_results(
    results_file: str,
    *,
    indexes: Sequence[int],
    interlayer_distance: float,
    output_path: str | None = None,
    output_dir: str | None = None,
    tolerance: int = 1,
    tolerance_float: float = 1e-4,
    zfix: float | None = None,
) -> List[MakeRun]:
    """Generate one or more structures from a finder results file."""

    resolved_indexes = [int(index) for index in indexes]
    runs: List[MakeRun] = []
    for index in resolved_indexes:
        run = generate_from_results(
            results_file,
            index=index,
            interlayer_distance=interlayer_distance,
            output_path=output_path if len(resolved_indexes) == 1 else None,
            output_dir=output_dir,
            tolerance=tolerance,
            tolerance_float=tolerance_float,
            zfix=zfix,
        )
        runs.append(run)
    return runs
